[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 5;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = decoder_inst/sclk;
GLOBAL_PRIMARY_0_DRIVERTYPE = CLKDIV;
GLOBAL_PRIMARY_0_LOADNUM = 51;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = FT601_CLK_c;
GLOBAL_PRIMARY_1_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_1_LOADNUM = 135;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = ber_proc/din_clk_N_1128;
GLOBAL_PRIMARY_2_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_2_LOADNUM = 15;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = decoder_inst/deserializer_inst/clk_s[1];
GLOBAL_PRIMARY_3_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_3_LOADNUM = 13;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = decoder_inst/sclk_derived_94;
GLOBAL_PRIMARY_4_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_4_LOADNUM = 10;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 8;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = ft601_comp/FT601_CLK_c_enable_238;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 34;
GLOBAL_SECONDARY_0_SIGTYPE = CE;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = ft601_comp/FT601_CLK_c_enable_241;
GLOBAL_SECONDARY_1_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_1_LOADNUM = 17;
GLOBAL_SECONDARY_1_SIGTYPE = CE;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = ft601_comp/n3604;
GLOBAL_SECONDARY_2_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_2_LOADNUM = 12;
GLOBAL_SECONDARY_2_SIGTYPE = RST;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = ft601_comp/FT601_CLK_c_enable_120;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 41;
GLOBAL_SECONDARY_3_SIGTYPE = CE+RST;
; Global secondary clock #4
GLOBAL_SECONDARY_4_SIGNALNAME = ft601_comp/FT601_CLK_c_enable_184;
GLOBAL_SECONDARY_4_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_4_LOADNUM = 20;
GLOBAL_SECONDARY_4_SIGTYPE = CE;
; Global secondary clock #5
GLOBAL_SECONDARY_5_SIGNALNAME = ft601_comp/FT601_CLK_c_enable_152;
GLOBAL_SECONDARY_5_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_5_LOADNUM = 17;
GLOBAL_SECONDARY_5_SIGTYPE = CE;
; Global secondary clock #6
GLOBAL_SECONDARY_6_SIGNALNAME = ft601_comp/FT601_CLK_c_enable_235;
GLOBAL_SECONDARY_6_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_6_LOADNUM = 16;
GLOBAL_SECONDARY_6_SIGTYPE = CE;
; Global secondary clock #7
GLOBAL_SECONDARY_7_SIGNALNAME = decoder_inst/rx_ready;
GLOBAL_SECONDARY_7_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_7_LOADNUM = 41;
GLOBAL_SECONDARY_7_SIGTYPE = CE+RST;
; Edge Clocks
EDGE_USED = 1;
; Edge clock #0
EDGE_0_SIGNALNAME = decoder_inst/deserializer_inst/eclko;
EDGE_0_DRIVERTYPE = CLK_PIN;
EDGE_0_LOADNUM = 2;
; I/O Bank 0 Usage
BANK_0_USED = 10;
BANK_0_AVAIL = 19;
BANK_0_VCCIO = 2.5V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 18;
BANK_1_AVAIL = 21;
BANK_1_VCCIO = 2.5V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 4;
BANK_2_AVAIL = 20;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 6;
BANK_3_AVAIL = 6;
BANK_3_VCCIO = 2.5V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 6;
BANK_4_AVAIL = 6;
BANK_4_VCCIO = 2.5V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 5;
BANK_5_AVAIL = 8;
BANK_5_VCCIO = 2.5V;
BANK_5_VREF1 = NA;
